### ISSUE TITLE
Motion correction for multiple tiff files

### ISSUE THREAD

**Issue by yatangli** [flatironinstitute/NoRMCorre#12]
Can this program combine multiple tiff files and then do the motion correction, and save the motion corrected tiff files?

**Comment by epnev** [comment]
@yatangli Yes, there are two ways you can deal with this: 
1) Create a for loop where you correct each file with the template you obtained from the previous one. See e.g., lines 5-40 in this [file](https://github.com/epnev/ca_source_extraction/blob/master/run_pipeline.m). You'll need to change the output _type to 'tiff' in the options. 
2) You can use [this function](https://github.com/simonsfoundation/NoRMCorre/blob/master/concatenate_files.m) to combine your files into one big file and then correct it. 

#1 is recommended if each file is long enough, so that a template can be created. #2 is recommended for short files.

Let me know if there are issues.
