### ISSUE TITLE
Unexpected effect of correct_bidirectional_offset function.

### ISSUE THREAD

**Issue by ehennestad** [flatironinstitute/NoRMCorre#14]
I am using the correct_bidirectional_offset to correct data after resonance scanning. We just found out that when using [col_shift, M] = correct_bidirectional_offset(Y, nFrames, us) the pixel values of the output is different than the pixel values of the input.

Whereas the pixel values for the input varies between 31040 and 65534, the pixel values of the output varies between 26849 and 71852.

I usually run the code with an upsampling factor of 10 (default). I tried running with the us variabel set to 1 and then I got the expected minimum and maximum values on the output.

**Comment by epnev** [comment]
The reason for this behavior has to do with the interpolation that is used when correcting for the offset or when applying the shifts. This happens when the shifts are fractional. For integer shifts then you just copy the values to the different pixels (which is why this was going away when you were not using upsampling). 

I was clipping each frame between its min and max value when using FFT shifts, however when there is an offset I switch to 'cubic' shifts, where I was not doing this clipping. I changed that now so the dynamic range should be preserved. Please note that there is no right or wrong choice in this case (at least to my opinion)

**Comment by ehennestad** [comment]
Thank you for the clarification:)
